// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL or DIRECT_URL for migrations (non-pooled connection required)
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
